#! /usr/bin/bash

### VARIABLES TO BE CONFIGURED BEFORE USING
export PASTAS_DIR=add
export USER_NAME=add

### VARIABLES THAT DO NOT NEED TO BE CONFIGURED
export PROJECTS_ROOT=$PASTAS_DIR/projects
export DELME_DIR=$PROJECTS_ROOT/delme

export CURRENT_HOME=$PROJECTS_ROOT
export CURRENT_HOMES=""

### VARIABLES THAT ARE NOT RECOMENDED TO BE CHANGED
export SCRIPT_DIR=$HOME/.script
export LIB_DIR=$SCRIPT_DIR/lib
export PROGRAMFILES_DIR="/c/Program Files"
export USERS_ROOT=/c/Users/
export USER_ROOT=USERS_ROOT/USER_NAME
export USER_LOCAL_APP_DATA="$USER_ROOT/AppData/Local"
export LAST_LOCATION=''