#! /usr/bin/bash

### VARIABLES TO BE CONFIGURED BEFORE USING
export PASTAS_DIR=/c/pastas
export USER_NAME=Jhost

### VARIABLES THAT DO NOT NEED TO BE CONFIGURED
export PROJECTS_ROOT=$PASTAS_DIR/projects
export DELME_DIR=$PROJECTS_ROOT/delme

export CURRENT_HOME=$PROJECTS_ROOT
export CURRENT_HOMES="$(cat "$HOME/.scripts_for_windows/.config/homes")"

### VARIABLES THAT ARE NOT RECOMENDED TO BE CHANGED
export SCRIPT_DIR=$HOME/.script
export LIB_DIR=$SCRIPT_DIR/lib
export PROGRAMFILES_DIR="/c/Program Files"
export USERS_ROOT=/c/Users/
export USER_ROOT=USERS_ROOT/USER_NAME
export USER_LOCAL_APP_DATA="$USER_ROOT/AppData/Local"
export LAST_LOCATION=''
export SCRIPTS_FOR_WINDOWS_DIR="$HOME/.scripts_for_windows"
export SCRIPTS_FOR_WINDOWS_SCRIPTS_DIR="$SCRIPTS_FOR_WINDOWS_DIR/.script"
export SCRIPTS_FOR_WINDOWS_CONFIG_DIR="$SCRIPTS_FOR_WINDOWS_DIR/.config"
export CONFIG_FILE="$SCRIPTS_FOR_WINDOWS_CONFIG_DIR/.config.sh"
export MANAGE_CD_HOMES_FILE="$SCRIPTS_FOR_WINDOWS_SCRIPTS_DIR/manage_cdhome.sh"