#! bin/bash

### VARIABLES TO BE CONFIGURED BEFORE USING
export PASTAS_DIR=''
export LAST_LOCATION=''

### VARIABLES THAT DO NOT NEED TO BE CONFIGURED
export PROJECTS_ROOT=$PASTAS_DIR/projects
export DELME_DIR=$PROJECTS_ROOT/delme

export CURRENT_HOME=$PROJECTS_ROOT

### VARIABLES THAT ARE NOT RECOMENDED TO BE CHANGED
export SCRIPT_DIR=$HOME/.script